import Head from 'next/head'
import Login from './login/index'
import React,{useState, useEffect} from 'react';
import { useSelector, useDispatch } from 'react-redux';
import {securityCheck} from '../redux/login/securitySlice.js';




export default function Home() {

  const dispatch = useDispatch();
  dispatch(securityCheck(false));

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Login/>
    </div>
  )
}
